config/routes.rb
App121::Application.routes.draw do
  match '/items/search(/:category)', :controller => 'items', :action => 'search'
  match '/reservations/search', :controller => 'reservations', :action => 'search'

  match '/reservations/load_court_reservations', :controller => 'reservations', :action => 'load_court_reservations'
  match '/reservations/load_equipment_reservations', :controller => 'reservations', :action => 'load_equipment_reservations'
 
  resources :items
  resources :categories
  resources :reservations

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  
  attr_accessible :description, :name
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/court.rb
class Court < ActiveRecord::Base
  has_and_belongs_to_many :reservations 
 
  attr_accessible :name

  validates_presence_of :name
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :reservations 
  
  attr_accessible :category_id, :description, :item_number, :purchase_date, :value

  validates_presence_of :category_id, :description, :item_number, :purchase_date, :value
  validates_numericality_of :category_id, :value, :item_number
  validates_format_of :value, :with => /^\d+??(?:\.\d{0,2})?$/
  validates_date :purchase_date
  validates_uniqueness_of :item_number, :scope => :category_id
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  has_and_belongs_to_many :courts
  has_and_belongs_to_many :items 

  attr_accessible :end_time, :number_of_participants, :reservation_date, :start_time, :user_id
  
  validates_presence_of :end_time, :start_time, :reservation_date, :user_id
  validates_numericality_of :number_of_participants, :greater_than_or_equal_to => 0
  validates_time :start_time, :after => Time.parse('8:00am'),
    									 :after_message => 'The start time must be after 8:00 am',
    									 :allow_nil => false
  validates_time :end_time, :before => Time.parse('11:59pm'),
  						    :after => :start_time,
  						    :after_message => 'The end time must be after the start time',
     						:before_message => 'The start time must be before 11:59 pm',
     						:allow_nil => false
     						
  validates_date :reservation_date
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
    @categories = Category.all		
	end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to category_path(@category)
      flash[:notice] = "Category saved successfully"
    else
      render(:new)
      flash[:notice] = "Could not save Category"
    end
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:student])
      redirect_to category_path
      flash[:notice] = "Category successfully updated"
    else
      render(:edit)
      flash[:notice] = "Category could not be updated!"
    end
  end

  def destory
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to category_path
      flash[:notice] = "Category has been removed"
    else
      redirect_to category_path
      flash[:error] = "Category could not be removed" 
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    
  end
  
  def search
	@items = Item.find_all_by_category_id(params[:category][:category])
  end
  
  def new
    @item = Item.new
  end
  
  def show
  	@item = Item.find(params[:id])
  	@category = Category.find(@item.category_id)
  end	
  
  def edit
  	@item = Item.find(params[:id])
  	@category = Category.find(@item.category_id)
  	@categories = Category.all
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to item_path(@item)
      flash[:notice] = "Item saved successfully"
    else
      render(:new)
      flash[:notice] = "Could not save Item"
    end
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to item_path
      flash[:notice] = "Item successfully updated"
    else
      @category = Category.find(@item.category_id)
      render(:edit)
      flash[:notice] = "Item could not be updated!"
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      redirect_to items_path
      flash[:notice] = "Item has been removed"
    else
      redirect_to items_path
      flash[:error] = "Item could not be removed"
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
  
  end
    
  def show
	@reservation = Reservation.find(params[:id])
  end
  
  def new 
    @close_time = Time.parse('11:59pm')
    @current_time = Time.parse('12:00pm')
    @time_array = []
    while @current_time < @close_time
    	@time_array << @current_time
    	@current_time = (@current_time + 60*30)
    end
    @reservation_date = Date.today
    @reservation_start_time = Time.parse('12:00pm')
    @reservation_end_time = Time.parse('11:30pm')
    
    @reservation = Reservation.new
    @reservation.reservation_date = @reservation_date
    @reservation.start_time = @reservation_start_time
    @reservation.end_time = @reservation_end_time
  end
  
  def create
    @close_time = Time.parse('11:59pm')
    @current_time = Time.parse('12:00pm')
    @time_array = []
    
    while @current_time < @close_time
    	@time_array << @current_time
    	@current_time = (@current_time + 60*30)
    end
    
    
	@reservation = Reservation.new
	@reservation.reservation_date = params[:reservation][:reservation_date]
	@reservation.start_time = params[:reservation][:start_time]
	@reservation.end_time = params[:reservation][:end_time]
	@reservation.number_of_participants = params[:reservation][:number_of_participants]
	@reservation.user_id = params[:reservation][:user_id]
	
	@reservation_items = params[:items]
	@reservation_courts = params[:reservation][:court_ids]
	
	if @reservation_courts != nil
		@reservation_courts.each do |court|
			if court != ""
				@temp_court = Court.find_by_id(court)
				@reservation.courts << @temp_court
			end
		end
	end
	
	if @reservation_items != nil
		@reservation_items.each do |i|
			@temp_item = Item.find_by_id(i)
			@reservation.items << @temp_item
		end
	end
	
	if @reservation.save
      redirect_to reservation_path(@reservation)
      flash[:notice] = "Item saved successfully"
    else
      @reservation_date = @reservation.reservation_date
      @reservation_start_time = @reservation.start_time
      @reservation_end_time = @reservation.end_time
      render(:new)
      flash[:notice] = "Could not save Item"
    end
		
  end
  
  def destroy
    @r = Reservation.find(params[:id])
    if @r.destroy
      redirect_to "/reservations/search"
      flash[:notice] = "Category has been removed"
    else
      redirect_to "/reservations/search"
      flash[:error] = "Category could not be removed" 
    end
  end
  
  def search
  	if params[:reservation] != nil
  		begin
  			date = Date.parse(params[:reservation][:reservation_date])
  		rescue
  			date = nil
  		end
  		
  		user = params[:reservation][:user_id]
  	end
  	
  	if date != nil
  		if user != ""
  			@reservations = Reservation.find(:all, :conditions => ["reservation_date = ? and user_id = ?",date,user])
  		else
  			@reservations = Reservation.find(:all, :conditions => ["reservation_date = ?",date])
  		end
  	elsif user != nil
  		@reservations = Reservation.find(:all, :conditions => [" user_id = ?",user])
  	end
  	
  end
  
  def load_equipment_reservations
    @date = params[:date]
    @start = params[:start]
  	@end = params[:end]
  	
    @reservation_date = Date.parse(@date)
    @reservation_start_time = Time.parse(@start)
    @reservation_end_time = Time.parse(@end)
  	
  	respond_to do |format|
  		format.js{render :layout=>false}
  	end
  end
  
  def load_court_reservations
  	@date = params[:date]
  	if @date != nil
  		@reservation_date = Date.parse(@date)
  	end
  	
    @close_time = Time.parse('11:59pm')
    @current_time = Time.parse('12:00pm')
    @time_array = []
    
    while @current_time < @close_time
    	@time_array << @current_time
    	@current_time = (@current_time + 60*30)
    end
    
  	respond_to do |format|
  	    format.js {render :layout=>false}
  	end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/categories/_category.html.erb
<%= link_to "#{category.name}", category_path(category) %>
<%= link_to "Edit", edit_category_path(category) %>
<%= button_to "Delete", category, :method => :delete %>
<br />

app/views/categories/_form.html.erb
<%= semantic_form_for @category do |form| %>
	<%= form.inputs do %>
		<%= form.input :name %>
		<%= form.input :description %>
	<% end %>
	<%= form.actions do %>
		<%= form.action :submit, :as => :button %>
	<% end %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category <%= "#{@category.name}" %></h1>
<%= render 'form' %>
<% link_to "Back", category_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<p><%= link_to "New Category", new_category_path %></p>
<%= render @categories %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>
<%= link_to "Back", categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p><%= @category.description %> </p>
<%= link_to "Back", categories_path %>

app/views/items/_form.html.erb
<%= semantic_form_for @item do |form| %>
	<%= form.inputs do %>
		<%= form.input :category_id , :as => :select,  :collection => Category.all%>
		<%= form.input :item_number %>
		<%= form.input :description %>
		<%= form.input :purchase_date, :as => :string, :input_html => { :id => "datepicker" } %>
		<%= form.input :value %>
	<% end %>
	<%= form.actions do %>
		<%= form.action :submit, :as => :button %>
	<% end %>
<% end %>

<script type="text/javascript">
	$('#datepicker').datepicker({ dateFormat: "yy-mm-dd" });
</script>

app/views/items/_item.html.erb
<%= link_to "#{item.category.name} - Item ##{item.item_number}", item_path(item) %>
<%= link_to "Edit", edit_item_path(item) %>
<%= button_to "Delete", item, :method => :delete %>
<br />

app/views/items/edit.html.erb
<h1><%= "Editing #{@category.name} - Item ##{@item.item_number}" %></h1>
<%= render 'form' %>
<%= link_to "Back to all Items", items_path %>

app/views/items/index.html.erb
<h1>Select A Category to Find Items</h1>
<%= semantic_form_for :category, :url => 'items/search' do |form| %>
	<%= form.inputs do %>
		<%= form.input :category, :as => :select, :collection => 
		Category.order("name asc").map{ |c| [c.name, c.id]} %>
	<% end %>
	<%= form.actions do %>
		<%= form.action :submit, :as => :button %>
	<% end %>
<% end %>

<p><%= link_to "Create a New Item", new_item_path %></p>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render 'form' %>
<%= link_to "Back to Item Search", items_path %>

app/views/items/search.html.erb
<h1>Select A Category</h1>
<p><%= link_to "New Item", new_item_path %></p>
<%= render @items %>
<p><%= link_to "Back to Item Search", items_path %></p>

app/views/items/show.html.erb
<h1><%= "Category: #{@category.name}" %></h1>
<p>
<%= "Item Number: #{@item.item_number}" %> <br />
<%= "Description: #{@item.description}" %> 
</p>
<%= link_to "Back to all Items", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App121</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_court_reservations_table.html.erb
	<div id="court_reservation_div">
	<h3>Court Reservations for <%= @reservation_date %></h3>
			
	<table border="3">
		<tr><td colspan="<%= Court.all.size+1 %>" style="text-align:center;"><button type="button" id="refresh" onclick='reloadCourtReservations()'>Refresh</Button></td></tr>
		<tr>
			<th>Times</th>
			<% Court.all.each do |court| %>
				<th> <%= court.name%> </th>
			<% end %>
		</tr>
			<% @time_array.each do |time|%>
				<tr>
					<td><%= time.strftime("%I:%M%p") %></td>
					<% Court.all.each do |court| %>
						<% if @r = court.reservations.detect {|r| (r.reservation_date == @reservation_date) && (time.strftime("%H:%M%p") >= r.start_time.strftime("%H:%M%p")) && time.strftime("%H:%M%p") <= r.end_time.strftime("%H:%M%p")} %>
							<td style="background:red;"><%= link_to "CLOSED", reservation_path(@r) %></td>
						<%else%>
							<td style="background:lightgreen;">OPEN</td>
						<%end%>
					<% end %>
				</tr>
			<% end %>
	</table>
	</div>

app/views/reservations/_equipment_reservations_partial.html.erb
<div id="all-items">
    <h2 class="ui-widget-header">Items</h2>
    <div id="catalog">
    	<% Category.all.each do |cat| %>
        	<h2><a href="#"><%= cat.name %></a></h2>
        	<div>
            	<ul>
            		<% Item.find_all_by_category_id(cat.id).each do |item| %>
            		<% @r = item.reservations.detect{|r| r.reservation_date == @reservation_date && ((@reservation_start_time.strftime("%H:%M%p") >= r.start_time.strftime("%H:%M%p") && @reservation_start_time.strftime("%H:%M%p") < r.end_time.strftime("%H:%M%p")) || (@reservation_end_time.strftime("%H:%M%p") > r.start_time.strftime("%H:%M%p") && @reservation_end_time.strftime("%H:%M%p") <=  r.end_time.strftime("%H:%M%p")) || (@reservation_start_time.strftime("%H:%M%p") < r.start_time.strftime("%H:%M%p") && @reservation_end_time.strftime("%H:%M%p") >  r.end_time.strftime("%H:%M%p")))} %>
            		<%if !@r %>
                		<li class="available"><div class="item"><span class="item-name"><%= "#{cat.name} ##{item.item_number}" %></span><span class="item-id"><%= item.id %></span></div></li>
                	<% else %>
                		<li class="reserved"><div class="reserved_item"><span class="item-name"><%= "#{cat.name} ##{item.item_number}" %></span><br /><span class="reserved_text"><%= "Reserved from #{@r.start_time.strftime("%I:%M%p")} until #{@r.end_time.strftime("%I:%M%p")}"%></span></div></li>
                	<% end %>
                	<% end %>
            	</ul>
        	</div>
        <% end %>
    </div>
</div>

<div id="reservation-cart">
    <h2 class="ui-widget-header">Equipment Reservation Cart</h2>
    <div class="ui-widget-content">
    	<div class = "cart-head">
    		<span class="name">Item Name</span>
    	</div>
        <ul id="reservation-cart-list">
        <% if @reservation_items != nil %>
        	<% @reservation_items.each do |i| %>
        		<% @item = Item.find_by_id(i) %> 
        		<li>
        		<input type="hidden" name="items[]" value="<%=@item.id%>">
        		<button type="button" class="delete" id="<%=@item.id%>">✕</button>
            	<span class="name"> <%= "#{@item.category.name} ##{@item.item_number}" %></span>
            	</li>        		
        	<% end %>
        <% end %>	
        </ul>
    </div>
</div>
<div class="clear"></div>

app/views/reservations/_form.html.erb
<%= semantic_form_for @reservation do |form| %>
	<%= form.inputs do %>
		<%= form.input :user_id %>
		<%= form.input :number_of_participants %>
		<%= form.input :reservation_date, :as => :string, :input_html => { :id => "reservationDatePicker" }%>
		<%= form.input :courts, :as => :check_boxes, :include_blank => false, :collection => Court.all%>
		<%= form.input :start_time, :as => :select, :collection => @time_array.map{|t| t.strftime("%I:%M%p")}, :include_blank => false,:input_html => { :id => "reservationStartTime" } %>
		<%= form.input :end_time, :as => :select, :collection => @time_array.map{|t| t.strftime("%I:%M%p")}, :include_blank => false,:input_html => { :id => "reservationEndTime" } %>
	<% end %>
	
	<label>
  		<input type="checkbox" id="show_court_reservations_checkbox" title="Show Open and Reserved Court Times" onchange='showCourtReservations(this);'>
  			Show Open and Reserved Court Times for this Reservation Date
	</label>
	<br />
	
	<div id="update_content" style="display:none;">		
		<%= render 'court_reservations_table' %>
	</div>
	
	<label>
  		<input type="checkbox" id="show_equipment_reservations_checkbox" title="Add Equipment to this Reservation" onchange='showEquipmentReservation(this);'>
  			Add Equipment to this Reservation
	</label>
	<br />
	
<div id="equipment_reservation">
	<%= render 'equipment_reservations_partial' %>
</div>
	
	<%= form.actions do %>
		<%= form.action :submit, :as => :button %>
	<% end %>
<% end %>

<style>

	/* equipment reservation divs*/
	#all-items
	{
		width:400px;
		float:left;
	}
	#reservation-cart
	{
		width:300px;
		float:left;
		margin-left:50px;
	}
	#equipment_reservation
	{
		display:none;
	}
	.item
	{
		margin-top:5px;
		text-align:center;
		padding:3px;
		margin-bottom:8px;
		border:1px solid black;
	}
	.item:hover
	{
		background:lightgrey;
		cursor:move;
	}
	.item-id
	{
		display:none;
		font-size:1px;
	}
	.clear
	{
		clear:both;
	}
	
	/*Reserved Items*/
	.reserved_item{
		margin-top:5px;
		text-align:center;
		padding:3px;
		margin-bottom:8px;
		border:1px solid black;
		background:grey;
	}
	.reserved_text{
		font-size:12px;
		font-style:italic;
	}
	
	/* cart */
	#reservation-cart .cart-head {
    	overflow: hidden;
    	margin: 0 10px;
    	height: 26px;
    	line-height: 26px;
    	color: #666;
    	border-bottom: 1px solid #ddd;
	}
	#reservation-cart .cart-head .name { float: left }
	#reservation-cart ul { padding-bottom: 10px }

	#reservation-cart ul li {
    	position: relative;
    	clear: both;
    	overflow: hidden;
    	margin: 0 10px;
    	height: 26px;
    	line-height: 32px;
    	border-bottom: 1px dashed #eee;
	}
	
	
	/* delete button */
	#reservation-cart ul li button.delete {
	margin-right:10px;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
    filter: alpha(opacity = 100);
    opacity: 1;
    width: 20px;
    line-height: 20px;
    height: 20px;
    text-align: center;
    font-size: 11px;
    border: 0;
    color: #EE5757;
    background-color: #eee;
    border-radius: 3px;
    cursor: pointer;
    -webkit-transition: opacity .2s ease;
    -moz-transition: opacity .2s ease;
    -o-transition: opacity .2s ease;
    -ms-transition: opacity .2s ease;
    transition: opacity .2s ease;
	}
	#reservation-cart ul li button.delete:hover {
    	color: #fff;
    	background-color: #ffa0a3;
	}
</style>

<script type="text/javascript">

	$(document).ready(function() {
	
		$("#reservationDatePicker").change(function(){
			reloadCourtReservations();
			reloadEquipmentReservations();
			
		});
		$("#reservationStartTime").change(function(){
			reloadEquipmentReservations();
			
		});
		$("#reservationEndTime").change(function(){
			reloadEquipmentReservations();
			
		});
		$('#reservationDatePicker').datepicker({ dateFormat: "yy-mm-dd" });
		
		setupEquipmentShoppingCart();
	});
		function setupEquipmentShoppingCart(){
			//shopping cart stuff
			$( "#catalog" ).accordion({
				collapsible:true,
				heightStyle: "content",
				active: false
			});
        	$( ".available" ).draggable({
        		cursor: "move", 
        		cursorAt: { top: 10, left: 56 },
            	appendTo: "body",
            	helper: "clone"
        	});
        	$( "#reservation-cart" ).droppable({
            	activeClass: "ui-state-default",
            	hoverClass: "ui-state-hover",
            	accept: ":not(.ui-sortable-helper)",
            	drop: function( event, ui ) {
                	//ui.draggable.remove().html();
                	var cart = $(this),move = ui.draggable;
                	addCart(cart,move);
            	}
        	});
		}
		
		function reloadCourtReservations(){
 			var date = $("#reservationDatePicker").val();
  			$.ajax({
    			url: '/reservations/load_court_reservations',
    			data: {'date': date},
    			dataType: 'script',
    			type: 'GET',
    			success: function(data) { data }
  			});
		}
		
		function reloadEquipmentReservations(){
			if($("#show_equipment_reservations_checkbox").attr('checked'))
			{
				fetchEquipmentReservations();
			}
		}
		
		function fetchEquipmentReservations(){
 			var date = $("#reservationDatePicker").val();
 			var start= $('#reservationStartTime').val(); 
 			var end= $('#reservationEndTime').val();
  			$.ajax({
    			url: '/reservations/load_equipment_reservations',
    			data: {'date': date,
    				   'start':start,
    				   'end':end},
    			dataType: 'script',
    			type: 'GET',
    			success: function(data) { data }
  			});
		}
		
		function addCart(cart, move) {
			var id = move.find(".item-id").html();
			
			var alreadyInCart = false;
			
			$("input:hidden").each(function (){
				if($(this).val() == id)
				{
					alreadyInCart = true;
				}

			});
			
			if(!alreadyInCart)
			{
			cart.find("ul").append('<li>'
    		+ '<input type="hidden" name="items[]" value="'+ id +'">'
    		+ '<button type="button" class="delete" id="' + id + '">✕</button>'
            + '<span class="name">' + move.find(".item-name").html() + '</span></li>');
            }
    		
		}
		
		function showCourtReservations(cb){
			if(cb.checked)
			{
				$('#update_content').css('display','inline');
			}
			else
			{
				$('#update_content').css('display','none');
			}
		}
		
		function showEquipmentReservation(cb){
			if(cb.checked)
			{
				reloadEquipmentReservations();
				$('#equipment_reservation').css('display','inline');
			}
			else
			{
				$('#equipment_reservation').css('display','none');
				items = [];
				$('#reservation-cart-list').empty();
				
			}
		}

		
		$("#reservation-cart ul li button.delete").live("click", function () {
    		$(this).closest("li").remove();
    		//item array management
    		var id = $(this).id;
    		var position = $.inArray(id,items);
    		if(position != -1)
    		{
    			items.splice(position,1);
    		}
		});
	

</script>

app/views/reservations/create.html.erb
<%= "#{@new_reservations}" %>
<br />
<%= "#{@starttime}" %>
<br />
<%= "#{@endtime}" %>

app/views/reservations/index.html.erb
<h1> Reservations </h1>
<p>
	<%= link_to "Create a Reservation", new_reservation_path%>
	<br />
	<%= link_to "Search for a Reservation", "/reservations/search"%>
</p>

app/views/reservations/load_court_reservations.js.erb
$("#update_content").html("<%= escape_javascript(render(:partial => 'court_reservations_table')) %>" );

app/views/reservations/load_equipment_reservations.js.erb
$("#equipment_reservation").html("<%= escape_javascript(render(:partial => 'equipment_reservations_partial')) %>" );
setupEquipmentShoppingCart();

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= render 'form' %>
<%= link_to "Back", reservations_path %>

app/views/reservations/search.html.erb
<h1>Search for a Reservation</h1>
<%= semantic_form_for :reservation, :url => '/reservations/search' do |form| %>
	<%= form.inputs do %>
		<%= form.input :user_id %>
		<%= form.input :reservation_date, :input_html => { :id => "reservationDatePicker" } %>
	<% end %>
	<%= form.actions do %>
		<%= form.action :submit, :as => :button, :label => "Search" %>
	<% end %>
<% end %>
<% if @reservations != nil && @reservations.count > 0%>
	<table border="1">
	<tr><th>User</th><th>Reservation Id</th><th>Reservation Date</th><th>Reservation Start Time</th><th>Reservation End Time</th><th></th><th></th></tr>
	<% @reservations.each do |r|%>
		<tr>
			<td><%=r.user_id%></td>
			<td><%=r.id%></td>
			<td><%=r.reservation_date%></td>
			<td><%=r.start_time.strftime("%I:%M%p")%></td>
			<td><%=r.end_time.strftime("%I:%M%p")%></td>
			<td><%= link_to "View Reservation", reservation_path(r) %></td>
			<td><%= button_to "Delete", r, :method => :delete %></td>
		</tr>
	<% end %>
	</table>
<% elsif @reservations != nil && @reservations.count == 0 %>
	No Reservations Found
<% end %>

<p><%= link_to "Create a New Reservation", new_reservation_path %></p>
<p><%= link_to "Back to Reservations Main", reservations_path %></p>


<script type="text/javascript">
	$('#reservationDatePicker').datepicker({ dateFormat: "yy-mm-dd" });
</script>

app/views/reservations/show.html.erb
<h1><%= "Reservation #{@reservation.id}" %> </h1>
<p>
<%= "User Id: #{@reservation.user_id}" %> 
</p>
<p>
<%= "Reservation Date: #{@reservation.reservation_date}" %> <br />
<%= "Start Time: #{@reservation.start_time}" %> <br />
<%= "End Time: #{@reservation.end_time}" %> <br />
<%= "Number of Participants: #{@reservation.number_of_participants}" %> <br />
<%= "Reserved Courts: "%> <br />
<% @reservation.courts.each do |c|%>
	&nbsp;<%= " #{c.name} " %><br />
<% end %>
<%= "Reserved Items:" %><br />
<% @reservation.items.each do |i|%>
	&nbsp;<%= " #{i.category.name} ##{i.item_number} " %><br />
<% end %>

</p>
<%= link_to "Back to Reservations Main Page", reservations_path %>